### ISSUE TITLE
Database scanning error.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#192]
From #145, #187 and mailing list threads.

Some of us are running into

```
Something went wonky
[...]

Error:
undefined method `downcase!' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:25:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:109:in `new'
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:109:in `block (2 levels) in scan_databases_dir'
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:106:in `each_line'
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:106:in `block in scan_databases_dir'
[...]
```

I'm able to reproduce this error if:
1. The database files have incorrect permission (like, 000 or unreadable by the user running SequenceServer).
2. The database file is corrupt.

In both the cases SequenceServer should now output an error saying:

```
Error obtaining BLAST databases.
Tried: blastdbcmd ...
Error:
... error msg from BLAST ...
```

However, some users (like in #147) are reporting this error being caused by FASTA defline being too long or because defline contains funky characters. I haven't been able to reproduced this neither on Linux nor on Mac. Neither on 32bit system, nor on 64 bit system.

Version 1.0.3 tries to output a more informative message if a user runs into this error. Hopefully that will shed some light on this issue.

**Comment by yeban** [comment]
Fixed in 1.0.4.
