### ISSUE TITLE
Ox::ParseError - invalid format, elements overlap at line ..., column ... [parse.c:561]

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#194]
From - https://groups.google.com/forum/#!topic/sequenceserver/QbE11EMQoEo

I can reproduce the error with Chris' XML file, and the error does look to be what Chris reported. Malformed XML: `<Iteration>` and `<Iteration_hits>` elements do not have a closing tag. Things seem to work if I manually add the corresponding closing tags.

The XML is generated malformed probably due to the following error raised during archive file to XML conversion with `blast_formatter`:

```
Error: Failed s_BlastXMLAddIteration Q(0/1NCBI C++ Exception:
    T0 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_10349_130.14.22.10_9008__PrepareRelease_Linux64-Centos_1414443165/c++/compilers/unix/../../src/objtools/alnmgr/alnvec.cpp", line 902: Error: ncbi::objects::CAlnVec::TranslateNAToAA() - CAlnVec::TranslateNAToAA(): NA size expected to be divisible by 3
```

A gist of the XML and how to reproduce the issue - https://gist.github.com/yeban/b6a2c8fd082acc3e1371

Discussing if Ox can be lenient here - https://github.com/ohler55/ox/issues/111.

**Comment by yeban** [comment]
@wwood What do you think? Is this a bug in BLAST or something wrong with Chris' and Tim's FASTA files?

**Comment by yeban** [comment]
SequenceServer doesn't check if `blast_formatter` ran successfully. It assumes that once archive files has been successfully generated, conversion from archive to xml or tsv will not be problematic. Clearly, we will have to do error checking in the conversion step as well and surface appropriate error message to the user.

**Comment by wwood** [comment]
Ho @yeban I don't have much to add - my suspicion is that it is a bug in blast, but need to reproduce on the cmdline in order to usefully report

**Comment by yeban** [comment]
Pulling @tomas-pluskal into this thread who last reported the issue here - https://groups.google.com/d/msg/sequenceserver/72fE1lE_J7k/DlBJwc3VCAAJ

**Comment by tomas-pluskal** [comment]
Hi.

I just installed 1.1.0-beta10 and created two files:

**rand1.fasta:**
````
>random_sequence
CATGGAGTGTCCTAGTAGTAAAACGAAAACCCCAGAACGTTTCTTAGACTCACCACCCCACCCCTGACAACTCCCGTAGG
````

**rand2.fasta:**
````
>random_sequence
TCGATTAAAATAAAGCTTGTCATGGAGTGTCCTAGTAGTAAAACGAAAACCCCAGAACGTTTCTTAGACTCACCACCCCACCCCTGACAACTCCCGTAGG
````

Then I blasted SWSVLVVKRKPQNVS*THHPTPDNSRR

Result:
````
Ox::ParseError
invalid format, elements overlap at line 28, column 26 [parse.c:590]

/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/blast/report.rb:134:in `parse'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/blast/report.rb:134:in `parse_xml'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/blast/report.rb:49:in `generate'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/report.rb:27:in `initialize'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/blast/report.rb:26:in `initialize'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/report.rb:15:in `new'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/report.rb:15:in `generate'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver/routes.rb:87:in `block in <class:Routes>'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `block in compile!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta10/lib/sequenceserver.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
````

Also pulling @photocyte.

**Comment by tomas-pluskal** [comment]
Could be dependent on blast version? We have ncbi-blast-2.6.0+

**Comment by yeban** [comment]
Thanks @tomas-pluskal. Turns out I was using another incorrect test dataset from the same thread.

**Comment by tomas-pluskal** [comment]
Have you tried contacting the BLAST people about this issue?
