### ISSUE TITLE
BLAST search fails when using BLAST+ 2.4

### ISSUE THREAD

**Issue by cmdcolin** [wurmlab/sequenceserver#296]
I was getting an error running the master branch of sequenceserver with blast+ 2.4.0. I installed 2.3.0 and it worked without changes though, so I am suspecting that BLAST+ 2.4.0 is the issue

Error dump after starting up server locally with `bundle exec bin/sequenceserver -D` and submitting a blastn request.

```
2016-08-22 09:53:13 - NoMethodError - undefined method `[]' for nil:NilClass:
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:128:in `block in extract_hits'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:125:in `each'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:125:in `extract_hits'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:116:in `block in extract_query'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:114:in `each'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:114:in `extract_query'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:52:in `generate'
```

I added some debug statements just to see if I could resolve it but it wasn't exactly clear what the issue was. Maybe something to do with ncbi blast assigning it's own IDs like "gnl|BL_ORD_ID|0"

```
[2016-08-22 10:07:16] DEBUG  Executing: blast_formatter -archive '/Users/biocmd/.sequenceserver/f3c19913-84aa-41ac-b072-53ebec832ad6/rfile' -outfmt '5 ' -out '/Users/biocmd/.sequenceserver/f3c19913-84aa-41ac-b072-53ebec832ad6/sequenceserver-xml_report.xml' 2> /dev/null
[2016-08-22 10:07:17] DEBUG  Executing: blast_formatter -archive '/Users/biocmd/.sequenceserver/f3c19913-84aa-41ac-b072-53ebec832ad6/rfile' -outfmt '7 qseqid sseqid sscinames qcovs qcovhsp' -out '/Users/biocmd/.sequenceserver/f3c19913-84aa-41ac-b072-53ebec832ad6/sequenceserver-__ssparse_report.tsv' 2> /dev/null
hit_info
nil
cov_info
{"Query_1"=>{"scf1117875582023"=>["N/A", "97", ["35", "35", "35", "35", "44", "35"]]}}
cov_info query
{"scf1117875582023"=>["N/A", "97", ["35", "35", "35", "35", "44", "35"]]}
n
["1", "gnl|BL_ORD_ID|0", "scf1117875582023", "0", "1683196", [["1", "22.9267", "24", "3.37767", "23", "34", "283662", "283651", "1", "-1", "12", "12", "0", "12", "TACGTACGCACA", "TACGTACGCACA", "||||||||||||"], ["2", "22.9267", "24", "3.37767", "2", "13", "930750", "930761", "1", "1", "12", "12", "0", "12", "CAGCGTCATCGA", "CAGCGTCATCGA", "||||||||||||"], ["3", "22.9267", "24", "3.37767", "23", "34", "1073462", "1073451", "1", "-1", "12", "12", "0", "12", "TACGTACGCACA", "TACGTACGCACA", "||||||||||||"], ["4", "22.9267", "24", "3.37767", "2", "13", "1081428", "1081417", "1", "-1", "12", "12", "0", "12", "CAGCGTCATCGA", "CAGCGTCATCGA", "||||||||||||"], ["5", "22.9267", "24", "3.37767", "17", "31", "1265738", "1265724", "1", "-1", "14", "14", "0", "15", "GCTAGCTACGTACGC", "GCAAGCTACGTACGC", "|| ||||||||||||"], ["6", "22.9267", "24", "3.37767", "11", "22", "1469270", "1469281", "1", "1", "12", "12", "0", "12", "CGATCAGCTAGC", "CGATCAGCTAGC", "||||||||||||"]]]
n[1]
"gnl|BL_ORD_ID|0"
query
#<struct SequenceServer::BLAST::Query report=#<SequenceServer::BLAST::Report:0x007f97d9e051f0 @job=#<SequenceServer::BLAST::Job:0x007f97d9e07428 @id="f3c19913-84aa-41ac-b072-53ebec832ad6", @method="blastn", @qfile="/Users/biocmd/.sequenceserver/f3c19913-84aa-41ac-b072-53ebec832ad6/query.fa", @databases=[#<struct SequenceServer::Database name="/Users/biocmd/Data/pyu_data/scf1117875582023.fa", title="scf1117875582023.fa", type="nucleotide", nsequences="1", ncharacters="1683196", updated_on="Aug 16, 2016  7:12 PM\n">], @options=" -outfmt '11 qcovs qcovhsp' -num_threads 1 -task blastn", @advanced_params={}, @completed_at=2016-08-22 10:07:13 -0500, @done=true, @success=true>, @querydb=[#<struct SequenceServer::Database name="/Users/biocmd/Data/pyu_data/scf1117875582023.fa", title="scf1117875582023.fa", type="nucleotide", nsequences="1", ncharacters="1683196", updated_on="Aug 16, 2016  7:12 PM\n">], @queries=[], @program="blastn", @program_version="BLASTN 2.4.0+", @params={"sc-match"=>"2", "sc-mismatch"=>"-3", "gap-open"=>"5", "gap-extend"=>"2", "filter"=>"L;m;", "evalue"=>"10"}, @stats={:nsequences=>"1", :ncharacters=>"1683196", :hsp_length=>"18", :search_space=>"26930848", :kappa=>"0.41", :labmda=>"0.625", :entropy=>"0.78"}>, number=1, def="Query_1", length=34, hits=[]>
query.id
"Query_1"
2016-08-22 10:07:17 - NoMethodError - undefined method `[]' for nil:NilClass:
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:142:in `block in extract_hits'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:125:in `each'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:125:in `extract_hits'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:116:in `block in extract_query'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:114:in `each'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:114:in `extract_query'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:52:in `generate'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/report.rb:27:in `initialize'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/blast/report.rb:25:in `initialize'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/report.rb:15:in `new'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/report.rb:15:in `generate'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver/routes.rb:84:in `block in <class:Routes>'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `block in compile!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /Users/biocmd/src/github.com/wurmlab/sequenceserver/lib/sequenceserver.rb:99:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
    /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
    /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [22/Aug/2016:10:07:16 CDT] "GET /f3c19913-84aa-41ac-b072-53ebec832ad6.json HTTP/1.1" 500 5293

```

**Comment by uludag** [comment]
I was also getting the first error (in report.rb line 128) for sometime, I have tried debugging it but have not been successful in finding the root of the problem, however I remember that  when I used earlier version of the BLAST (2.3) problem was still there.

In my test server, i temporarily use the following changes to let it working.  --mahmut

$ git diff lib/sequenceserver/blast/report.rb
diff --git a/lib/sequenceserver/blast/report.rb b/lib/sequenceserver/blast/report.rb
index 7cfad14..8e3b101 100644
--- a/lib/sequenceserver/blast/report.rb
+++ b/lib/sequenceserver/blast/report.rb
@@ -124,10 +124,12 @@ module SequenceServer
         return if hits_ir == ["\n"] # => No hits.
         hits_ir.each do |n|
           hit_info = cov_info[query.id][n[1]]
+          # if !hit_info.nil?
           hit = Hit.new(query, n[0], n[1], n[3], n[2], n[4],
-                        hit_info[1], hit_info[0], [])
-          extract_hsps(n[5], hit, hit_info[2])
+                        (!hit_info.nil? ? hit_info[1] : ""), (!hit_info.nil? ? hit_info[0] : ""), [])
+          extract_hsps(n[5], hit, (!hit_info.nil? ? hit_info[2] : ""))
           query.hits << hit
+          # end
         end
       end

**Comment by uludag** [comment]
Problem looks here, line 48 in lib/sequenceserver/blast/report.rb

`      ir = node_to_array(Ox.parse(File.read(xml)).root)`

BLAST has well defined XML and JSON outputs, it is difficult to understand why SequenceServer reads already constructed object to an array then  uses the arrays to access information while it is possible to use the BLAST output object directly? I am new to Ruby and to SequenceServer, it is likely that I am wrong with my comment.

I have debugged this problem further and have found that SequenceServer is failing when the BLAST xml reports use BLAST internal identifiers for the database sequences, such as in the following example.

`<Hit_id>gnl|BL_ORD_ID|2435</Hit_id>`

In the example reports I have, the field (Hit_def) next to the Hit_id field contains the actual sequence identifiers. Reading the hit identifiers from the Hit_def field allowed my test server to read/display the results that were failing earlier. This workaround was also used in [galaxy_blast project](https://github.com/peterjc/galaxy_blast/commit/7f3ededdedf2bb72dca302941fa7894546a693a1).

```
$ git diff lib/sequenceserver/blast/report.rb 
diff --git a/lib/sequenceserver/blast/report.rb b/lib/sequenceserver/blast/report.rb
index 7cfad14..6fce276 100644
--- a/lib/sequenceserver/blast/report.rb
+++ b/lib/sequenceserver/blast/report.rb
@@ -124,6 +124,9 @@ module SequenceServer
         return if hits_ir == ["\n"] # => No hits.
         hits_ir.each do |n|
           hit_info = cov_info[query.id][n[1]]
+          if hit_info.nil?
+            hit_info = cov_info[query.id][n[2].split(" ")[0]]
+          end
           hit = Hit.new(query, n[0], n[1], n[3], n[2], n[4],
                         hit_info[1], hit_info[0], [])
           extract_hsps(n[5], hit, hit_info[2])
```

**Comment by yeban** [comment]
Hey @cmdcolin. If it's not urgent to you, I would prefer to look into it the last thing before the next release. So that I have to catch up with BLAST only once.

**Comment by cmdcolin** [comment]
Not a problem to me. This just came up in local dev env

**Comment by yeban** [comment]
Works on 2.6.0+, so I guess we will just skip 2.4.0.

**Comment by ginac** [comment]
you need to use the flag -parse_seqids with makeblastdb
