### ISSUE TITLE
"NoMethodError - undefined method `root' for nil:NilClass" error message on macOS

### ISSUE THREAD

**Issue by hffqyd** [wurmlab/sequenceserver#346]
# Thanks for the amazing sequenceserver to run BLAST in an amazing way!

When I used it on macOS recently, there was a problem. Here is the error message below: 

```
NoMethodError - undefined method `root' for nil:NilClass:
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver/blast/report.rb:38:in `generate'
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver/blast/report.rb:21:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver/blast.rb:96:in `new'
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver/blast.rb:96:in `run'
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver/routes.rb:135:in `block in <class:Routes>'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/Library/Ruby/Gems/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-1.0.11/lib/sequenceserver.rb:92:in `call'
/Library/Ruby/Gems/2.3.0/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

Did I do something wrong?  What can I do to solve the problem? 

Thanks!

**Comment by yeban** [comment]
This happens when BLAST crashes and doesn’t generate any output. Re-installing BLAST should fix the issue. SequenceServer can download BLAST binaries for itself if BLAST is not already installed through other means (e.g., homebrew).

**Comment by hffqyd** [comment]
Thanks a lot for your help!
Re-installing the BLAST+ fixed the problem.
