### ISSUE TITLE
sequenceserver-1.1.0.beta5 fails to start

### ISSUE THREAD

**Issue by tomas-pluskal** [wurmlab/sequenceserver#358]
Hi, 

I am testing sequenceserver-1.1.0.beta5. It fails to start with some issues calling slop:

````
$ sequenceserver 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sequenceserver (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta5/bin/sequenceserver:156:in `block (2 levels) in <top (required)>'
	from /home/pluskal/.gem/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /home/pluskal/.gem/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta5/bin/sequenceserver:24:in `<top (required)>'
	from /home/pluskal/.gem/ruby/2.3.0/bin/sequenceserver:22:in `load'
	from /home/pluskal/.gem/ruby/2.3.0/bin/sequenceserver:22:in `<main>'
````

This is my environment:
````
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/pluskal/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/pluskal/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /home/pluskal/.gem/ruby/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/jdk1.8/bin
     - /home/pluskal/.gem/ruby/2.3.0/bin
     - /lab/solexa_weng/testtube/miniconda3/bin
     - /home/pluskal/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games


$ gem list

*** LOCAL GEMS ***

addressable (2.5.2)
bigdecimal (1.3.4, 1.2.8)
bundler (1.16.1)
capybara (3.0.2, 2.18.0)
childprocess (0.9.0)
codeclimate-test-reporter (1.0.8)
diff-lcs (1.3)
docile (1.3.0, 1.1.5)
domain_name (0.5.20180417)
ffi (1.9.23)
http-cookie (1.0.3)
io-console (0.4.6, 0.4.5)
json (2.1.0, 1.8.3)
json_pure (2.1.0, 1.8.6)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
mustermann (1.0.2)
netrc (0.11.0)
nokogiri (1.8.2)
ox (2.9.2, 2.4.12)
psych (3.0.2, 2.1.0)
public_suffix (3.0.2)
rack (2.0.5, 1.6.5)
rack-protection (2.0.1, 1.5.3)
rack-test (1.0.0)
rake (12.3.1, 10.5.0)
rdoc (6.0.3, 4.2.1)
rest-client (2.0.2)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-support (3.7.1)
rubyzip (1.2.1)
sauce_whisk (0.1.0)
selenium-webdriver (3.11.0)
sequenceserver (1.1.0.beta5)
simplecov (0.16.1, 0.13.0)
simplecov-html (0.10.2)
sinatra (2.0.1, 1.4.8)
slop (3.6.0)
tilt (2.0.8, 2.0.7)
unf (0.1.4)
unf_ext (0.0.7.5)
xpath (3.0.0)

````

**Comment by tomas-pluskal** [comment]
Note, I used the following commands to install the beta:
````
bundle install --path ~/.gem
gem build sequenceserver.gemspec
gem install --local --user-install sequenceserver-1.1.0.beta5.gem
````

**Comment by yeban** [comment]
It's not slop. The sequenceserver executable (`bin/sequenceserver`) is unable to load the rest of sequenceserver's code (`lib/sequenceserver.rb`).

I can't reproduce it, so I am not sure what could be causing the problem. I can only suggest that you either use bundler or gem, not both:

```
bundle install
bundle exec bin/sequenceserver
```

or

```
gem install --user-install --pre sequenceserver
```

**Comment by tomas-pluskal** [comment]
I see. 
Two observations: 
1. ````bundle exec bin/sequenceserver```` works
2. ````gem install --user-install --pre sequenceserver```` succeeds (1 gem installed), but trying to run ````sequenceserver```` afterwards results in the same error: 
````
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sequenceserver (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta5/bin/sequenceserver:156:in `block (2 levels) in <top (required)>'
	from /home/pluskal/.gem/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /home/pluskal/.gem/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta5/bin/sequenceserver:24:in `<top (required)>'
	from /home/pluskal/.gem/ruby/2.3.0/bin/sequenceserver:22:in `load'
	from /home/pluskal/.gem/ruby/2.3.0/bin/sequenceserver:22:in `<main>'
````

**Comment by tomas-pluskal** [comment]
Nevermind - running the following seems to have fixed the problem.
 ````
gem uninstall sequenceserver
gem install --user-install --pre sequenceserver
````
