### ISSUE TITLE
kernel_require.rb:55:in `require': cannot load such file

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#366]
Hello,
I tried to run the latest sequenceserver but ran into the following error:

```
$ docker run --rm -ti -p 4567:4567 -v $(pwd)/db:/db seqserver
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sequenceserver (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /sequenceserver-1.1.0.beta10/bin/sequenceserver:156:in `block (2 levels) in <main>'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /sequenceserver-1.1.0.beta10/bin/sequenceserver:24:in `<main>'
```

and here is my Dockerfile:

```
FROM debian:stretch-backports
RUN apt-get update  && apt-get install -y --no-install-recommends \
        build-essential \
        ruby ruby-dev \
        curl wget \
        gnupg \
        git \
        ncbi-blast+

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
        apt-get update  && apt-get install -y --no-install-recommends \
        nodejs npm && \
        rm -rf /var/lib/apt/lists/*

RUN wget -c https://github.com/wurmlab/sequenceserver/archive/1.1.0.beta10.tar.gz  && \
    gem install bundler && \
    tar xfvz 1.1.0.beta10.tar.gz && \
    cd sequenceserver-1.1.0.beta10 && \
    npm install && \
    bundle install --without=development

RUN mkdir /db
EXPOSE 4567
CMD /sequenceserver-1.1.0.beta10/bin/sequenceserver -d /db
```

What did I miss?

Thank you in advance.

Michal

**Comment by yeban** [comment]
Try setting working directory to `/sequenceserver-1.1.0.beta10` and using `bundle exec bin/sequenceserver -d /db` as the command.

**Comment by mictadlo** [comment]
Thank you it works. Please find below the update Docker file:
```
FROM debian:stretch-backports
RUN apt-get update  && apt-get install -y --no-install-recommends \
        build-essential \
        ruby ruby-dev \
        curl wget \
        gnupg \
        git \
        ncbi-blast+

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
        apt-get update  && apt-get install -y --no-install-recommends \
        nodejs npm && \
        rm -rf /var/lib/apt/lists/*

RUN wget -c https://github.com/wurmlab/sequenceserver/archive/1.1.0.beta10.tar.gz  && \
    apt-get update  && apt-get install -y --no-install-recommends zlib1g-dev && \
    gem install bundler && \
    tar xfvz 1.1.0.beta10.tar.gz && \
    cd sequenceserver-1.1.0.beta10 && \
    npm install && \
    bundle install

RUN mkdir /db
EXPOSE 4567
WORKDIR /sequenceserver-1.1.0.beta10
CMD bundle exec bin/sequenceserver -d /db
```

**Comment by yeban** [comment]
Thank you. I updated the current dockerfile with yours (with a few changes) - see e3df71c

**Comment by mictadlo** [comment]
How to use the Dockerfile with docker-compose because I ran into this problem:

```
$ docker-compose up
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
sequenceserver_1  | Enter taxid (optional): taxid should be a number
```
with the following docker-compose.yml file:

```
sequenceserver:
  build: sequenceserver
#  restart: always
  ports:
    - "4567:4567"
  volumes:
    - ./data/sequenceserver:/db 
```

What did I miss?

Thank you in advance

**Comment by mictadlo** [comment]
I changed the Entrypoint in the above dockerfile to `ENTRYPOINT bundle exec bin/sequenceserver -database_dir=/dbs --num_threads=4`.

In order to add new database I have to do:

```
> docker ps
> docker exec -it <Container id>  /bin/bash
> bundle exec bin/sequenceserver -d /dbs
``` 

Michal

**Comment by yeban** [comment]
If you have entrypoint as an array, like `ENTRYPOINT ["bundle", "exec", "bin/sequenceserver", "-d", "/db"]`, then you can add command line options to `docker run` command and these in turn will be passed to sequenceserver. Then you can:

```
# 4da9607ef6dc is my image id #

# Create BLAST databases and exit (-m / --make-blast-databases)
docker run -it -v $PWD:/db 4da9607ef6dc -m

# Now run server - since databases have been created before,
# this won't generate any further prompts.
docker run -it -p 4567:4567 -v $PWD:/db 4da9607ef6dc
```
