### ISSUE TITLE
1.1.0.beta12 failing with 'NoMethodError'

### ISSUE THREAD

**Issue by jogoodma** [wurmlab/sequenceserver#375]
I'm running version 1.1.0.beta12 from source (master branch) and having trouble running a test blastn run.  The BLAST job itself runs, I can see stdout and an empty stderr file, but when SequenceServer tries to render the result I get a modal with `NoMethodError` and `undefined method ``[]' for nil:NilClass` followed by a stack trace (below).  I'm using the auto downloaded blast v.2.6.0 and a database created at runtime.

```
[2018-09-26 13:23:43] DEBUG  {}
[2018-09-26 13:23:43] DEBUG  Executing: blast_formatter -archive '/home/jogoodma/.sequenceserver/3b20ab34-08a1-48d4-85ae-1c8129ffbeb0/stdout' -outfmt '5 '
[2018-09-26 13:23:43] DEBUG  Executing: blast_formatter -archive '/home/jogoodma/.sequenceserver/3b20ab34-08a1-48d4-85ae-1c8129ffbeb0/stdout' -outfmt '7 qseqid sseqid sscinames qcovs qcovhsp'
2018-09-26 13:23:43 - NoMethodError - undefined method `[]' for nil:NilClass:
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:120:in `block in extract_hits'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:109:in `each'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:109:in `extract_hits'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:101:in `block in extract_queries'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:99:in `each'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:99:in `extract_queries'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:56:in `generate'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/report.rb:26:in `initialize'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/blast/report.rb:26:in `initialize'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/report.rb:14:in `new'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/report.rb:14:in `generate'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver/routes.rb:87:in `block in <class:Routes>'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1634:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1634:in `block in compile!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
        /home/jogoodma/development/sequenceserver/lib/sequenceserver.rb:193:in `call'
        /home/jogoodma/development/sequenceserver/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [26/Sep/2018:13:23:43 EDT] "GET /3b20ab34-08a1-48d4-85ae-1c8129ffbeb0.json HTTP/1.1" 500 628
```

**Comment by jogoodma** [comment]
I'm getting the same error when using the `wurmlab/sequenceserver:latest` docker image.

**Comment by yeban** [comment]
Please could you share the file `/home/jogoodma/.sequenceserver/3b20ab34-08a1-48d4-85ae-1c8129ffbeb0/stdout` with me to help debug the issue.

If you could share the whole `/home/jogoodma/.sequenceserver/3b20ab34-08a1-48d4-85ae-1c8129ffbeb0/` folder, that would be even better. 

My email's in the README file or you could use a file-sharing website.

**Comment by jogoodma** [comment]
Here you go.

[blast_job.tar.gz](https://github.com/wurmlab/sequenceserver/files/2424795/blast_job.tar.gz)

**Comment by jogoodma** [comment]
A few more bits of information that may be useful.  When using the docker images, it looks like this broke between 1.1.0.beta10 and 1.1.0.beta11.  Also, it looks like it might be caused by the FASTA header format for the BLAST database.  If I reformat my BLAST dbs to use `>ID` it works, if I use `>gnl|dmel|ID` it fails.

**Comment by yeban** [comment]
Thanks. The ID scheme you are using is the critical bit. I am able to reproduce the issue. I will try to work out a fix and get back to you as soon as I can.

**Comment by yeban** [comment]
Thanks for reporting and helping fix this issue. Could you try and let me know if the problem persists?

beta1-beta10 docker tags are broken. They run version 1.0.x of SequenceServer rather than version 1.1.0-beta (see e3df71c7). Unfortunately, I haven't figured how to remove the old tags. Your looking into the different versions was helpful to connect the dots though :)
