### ISSUE TITLE
NoMethodError in 1.1.0.beta12

### ISSUE THREAD

**Issue by tomas-pluskal** [wurmlab/sequenceserver#379]
After performing a tblastn search:

undefined method `[]' for nil:NilClass
````
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:120:in `block in extract_hits'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:109:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:109:in `extract_hits'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:101:in `block in extract_queries'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:99:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:99:in `extract_queries'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:56:in `generate'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/report.rb:26:in `initialize'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/blast/report.rb:26:in `initialize'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/report.rb:14:in `new'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/report.rb:14:in `generate'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver/routes.rb:87:in `block in <class:Routes>'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `block in compile!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sequenceserver-1.1.0.beta12/lib/sequenceserver.rb:193:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
````

**Comment by yeban** [comment]
Works fine here. Is it possible that your issue is related to #375 which was fixed last to last week? Could you try running SequenceServer from git and let me know if that works for you?

**Comment by yeban** [comment]
git clone https://github.com/wurmlab/sequenceserver
    gem install bundler
    cd sequenceserver
    bundle install --without=development
    bundle exec bin/sequenceserver

**Comment by tomas-pluskal** [comment]
Yes, the issue seems to be fixed in the current git version.
