### ISSUE TITLE
Could not run 2.0.0.rc6 without internet connection

### ISSUE THREAD

**Issue by vks4git** [wurmlab/sequenceserver#482]
Hi,
I need to run SequenceServer without internet connection. I already [found out](https://github.com/wurmlab/sequenceserver/issues/458) that I should use blast+ 2.9.0, because newer versions send requests to NCBI servers. SequenceServer 1.0.14 works offline perfectly, but version 2.0.0.rc6 starts and immediately crashes with the following error:

```
[2020-08-11 11:51:25] WARN  Will listen on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--host option).
** SequenceServer is ready.
   Go to http://localhost:4567 in your browser and start BLASTing!
   To share your setup, please try one of the following:
/Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver.rb:258:in `ip_address': undefined method `ip_address' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver.rb:140:in `on_start'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver/server.rb:40:in `block in options'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:340:in `call_callback'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:167:in `block in start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver/server.rb:26:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver/server.rb:9:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/lib/sequenceserver.rb:120:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/bin/sequenceserver:391:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /Library/Ruby/Gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /Library/Ruby/Gems/2.3.0/gems/sequenceserver-2.0.0.rc6/bin/sequenceserver:48:in `<top (required)>'
	from /usr/local/bin/sequenceserver:22:in `load'
	from /usr/local/bin/sequenceserver:22:in `<main>' 
```

My configuration:
**OS:** OS X 10.14.6
**Ruby:** ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
**SequenceServer:** 2.0.0.rc6
**blast:** 2.9.0

**Comment by yeban** [comment]
Hi. Thanks for reporting the issue. Looks like the program didn't anticipate a case where no IP address would be found. I will look into it.

**Comment by yeban** [comment]
I have pushed a fix (gem install --pre sequenceserver). Let us know if you run into any other problems.
