### ISSUE TITLE
View Sequence link raises 

### ISSUE THREAD

**Issue by mjy** [wurmlab/sequenceserver#511]
RC8.  Docker image.

```
When I click 'BLASTN'
  and I get results
    then I click the link of a "# Similar sequence"
      and I see that sequence
        when when I click 'Sequence' 
          I raise an error
```

Link:

<img width="946" alt="Screen Shot 2021-01-16 at 10 07 10 AM" src="https://user-images.githubusercontent.com/22600/104816883-968dcc00-57e3-11eb-9b43-92ac403ed115.png">

Full stack:
```
/sequenceserver/lib/sequenceserver/sys.rb:83:in `sys'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `sys'
/sequenceserver/lib/sequenceserver/sequence.rb:203:in `run'
/sequenceserver/lib/sequenceserver/sequence.rb:182:in `initialize'
/sequenceserver/lib/sequenceserver/routes.rb:128:in `new'
/sequenceserver/lib/sequenceserver/routes.rb:128:in `block in <class:Routes>'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
/usr/local/bundle/gems/rack-2.1.2/lib/rack/deflater.rb:45:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/bundle/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
/sequenceserver/lib/sequenceserver.rb:114:in `call'
/usr/local/bundle/gems/rack-2.1.2/lib/rack/handler/webrick.rb:88:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by yannickwurm** [comment]
As indicated in discussion with @yeban , this is likely because the blast database was formatted without NCBI's  `-parse_seqids` option
