### ISSUE TITLE
FASTA Link raises

### ISSUE THREAD

**Issue by mjy** [wurmlab/sequenceserver#512]
Setup - see #511, but click the "FASTA" lnk.

Raise:

```json
{
    "message": "SequenceServer::CommandFailed",
    "title": "SequenceServer::CommandFailed",
    "more_info": "/sequenceserver/lib/sequenceserver/sys.rb:83:in `sys'\n/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `sys'\n/sequenceserver/lib/sequenceserver/sequence.rb:203:in `run'\n/sequenceserver/lib/sequenceserver/sequence.rb:182:in `initialize'\n/sequenceserver/lib/sequenceserver/routes.rb:135:in `new'\n/sequenceserver/lib/sequenceserver/routes.rb:135:in `block in '\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'\n/usr/local/bundle/gems/rack-2.1.2/lib/rack/deflater.rb:45:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'\n/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'\n/usr/local/bundle/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'\n/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'\n/sequenceserver/lib/sequenceserver.rb:114:in `call'\n/usr/local/bundle/gems/rack-2.1.2/lib/rack/handler/webrick.rb:88:in `service'\n/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'\n/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'\n/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'"
}
```

**Comment by guyleonard** [comment]
I have managed to replicate this same issue when I run makeblastdb without "-parse_seqids" where some accessions are over BLAST's 50 character limit.

Changing the accessions to be <=50 chars worked. Or you could compile the blast suite yourself and extend the 50 char limit upwards I guess...

**Comment by yeban** [comment]
Right. Sequence retrieval doesn't work if you don't use `-parse_seqids` option of makeblastdb. I am going to try to remove this restriction. It seems to be problematic for many of our users. But I am curious, if you are using 2.0-rc8, didn't seqserv complain that you have "incompatible" database and refused to start?
