### ISSUE TITLE
NoMethodError while running sequenceserver

### ISSUE THREAD

**Issue by aevenstad** [wurmlab/sequenceserver#638]
Hi,

I am getting this error when trying to run sequenceserver:

```
2023-05-12 15:27:09 - NoMethodError - undefined method `exists?' for File:Class:
	/Users/aev021/.gem/ruby/3.2.0/gems/sequenceserver-2.0.0/lib/sequenceserver/../../views/layout.erb:102:in `__tilt_1180'
	/Users/aev021/.gem/ruby/3.2.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `bind_call'
	/Users/aev021/.gem/ruby/3.2.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `evaluate'
	/Users/aev021/.gem/ruby/3.2.0/gems/tilt-2.1.0/lib/tilt/template.rb:109:in `render'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:863:in `render'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:872:in `block in render'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:872:in `catch'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:872:in `render'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:711:in `erb'
	/Users/aev021/.gem/ruby/3.2.0/gems/sequenceserver-2.0.0/lib/sequenceserver/routes.rb:70:in `block in <class:Routes>'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `block in compile!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1049:in `route_eval'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1078:in `block in process_route'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `catch'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `process_route'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1028:in `block in route!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `each'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `route!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1147:in `block in dispatch!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1142:in `dispatch!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `block in call!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `call!'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:945:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/rack-2.2.7/lib/rack/deflater.rb:44:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:218:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:2004:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `block in call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1780:in `synchronize'
	/Users/aev021/.gem/ruby/3.2.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/sequenceserver-2.0.0/lib/sequenceserver.rb:110:in `call'
	/Users/aev021/.gem/ruby/3.2.0/gems/rack-2.2.7/lib/rack/handler/webrick.rb:95:in `service'
	/Users/aev021/.gem/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/Users/aev021/.gem/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/Users/aev021/.gem/ruby/3.2.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

My machine is running macOS 10.15 
I have successfully ran `sequenceserver -m` to prep the databases and had no issues there.

I have tried to google a bit but this is my first encounter with Ruby/gems so any help is appreciated.

**Comment by aevenstad** [comment]
Installed with ruby 3.0.6 and everything seems to be running smoothly.
