### ISSUE TITLE
docker build for 2.1.0 release fails

### ISSUE THREAD

**Issue by nathanweeks** [wurmlab/sequenceserver#673]
With the 2.1.0 release,`docker build -t sequenceserver .` in a codespace fails with an error like the one observed in the [GitHub Actions Build workflow for the corresponding commit](https://github.com/wurmlab/sequenceserver/actions/runs/5699991196/job/15449420220):

```
 => [builder 5/6] RUN apt-get update && apt-get install -y --no-install-recommends     gcc make patch && rm -rf /var/lib/apt/  35.7s
 => ERROR [builder 6/6] RUN bundle install --without=development                                                               32.3s
------
 > [builder 6/6] RUN bundle install --without=development:
#14 4.521 Bundler 2.4.1 is running, but your lockfile was generated with 2.4.16. Installing Bundler 2.4.16 and restarting using that version.
#14 4.521 [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local without 'development'`, and stop using this flag
#14 6.497 Fetching gem metadata from https://rubygems.org/.
#14 6.574 Fetching bundler 2.4.16
#14 6.823 Installing bundler 2.4.16
#14 7.321 [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local without 'development'`, and stop using this flag
#14 9.109 Fetching gem metadata from http://rubygems.org/.........
#14 12.22 Resolving dependencies...
#14 12.47 Using bundler 2.4.16
#14 12.47 Fetching unf_ext 0.0.8.2
#14 12.48 Fetching http-accept 1.7.0
#14 12.57 Installing http-accept 1.7.0
#14 12.59 Fetching json_pure 2.6.3
#14 12.60 Installing unf_ext 0.0.8.2 with native extensions
#14 12.61 Installing json_pure 2.6.3
#14 12.65 Fetching mime-types-data 3.2023.0218.1
#14 12.69 Installing mime-types-data 3.2023.0218.1
#14 12.80 Using ruby2_keywords 0.0.5
#14 12.80 Fetching netrc 0.11.0
#14 12.80 Installing netrc 0.11.0
#14 12.82 Fetching ox 2.14.16
#14 12.87 Installing ox 2.14.16 with native extensions
#14 17.18 Fetching rack 2.2.7
#14 17.38 Installing rack 2.2.7
#14 17.50 Fetching rubyzip 2.3.2
#14 17.53 Installing rubyzip 2.3.2
#14 17.59 Fetching tilt 2.2.0
#14 17.60 Installing tilt 2.2.0
#14 17.67 Fetching slop 3.6.0
#14 17.70 Installing slop 3.6.0
#14 17.71 Fetching webrick 1.8.1
#14 17.74 Installing webrick 1.8.1
#14 17.76 Fetching mime-types 3.4.1
#14 17.79 Installing mime-types 3.4.1
#14 17.81 Fetching mustermann 2.0.2
#14 17.84 Installing mustermann 2.0.2
#14 31.80 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#14 31.80 
#14 31.80     current directory: /usr/local/bundle/gems/unf_ext-0.0.8.2/ext/unf_ext
#14 31.80 /usr/local/bin/ruby -I /usr/local/lib/ruby/3.2.0 extconf.rb
#14 31.80 checking for -lstdc++... no
#14 31.80 creating Makefile
#14 31.80 
#14 31.80 current directory: /usr/local/bundle/gems/unf_ext-0.0.8.2/ext/unf_ext
#14 31.80 make DESTDIR\= sitearchdir\=./.gem.20230802-6-waxjis
#14 31.80 sitelibdir\=./.gem.20230802-6-waxjis clean
#14 31.80 
#14 31.80 current directory: /usr/local/bundle/gems/unf_ext-0.0.8.2/ext/unf_ext
#14 31.80 make DESTDIR\= sitearchdir\=./.gem.20230802-6-waxjis
#14 31.80 sitelibdir\=./.gem.20230802-6-waxjis
#14 31.80 compiling unf.cc
#14 31.80 make: g++: Command not found
#14 31.80 make: *** [Makefile:216: unf.o] Error 127
#14 31.80 
#14 31.80 make failed, exit code 2
#14 31.80 
#14 31.80 Gem files will remain installed in /usr/local/bundle/gems/unf_ext-0.0.8.2 for
#14 31.80 inspection.
#14 31.80 Results logged to
#14 31.80 /usr/local/bundle/extensions/x86_64-linux/3.2.0/unf_ext-0.0.8.2/gem_make.out
#14 31.80 
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:102:in `run'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:51:in `block in make'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `each'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in `make'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:171:in `build_extension'
#14 31.80 /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:205:in `block in
#14 31.80 build_extensions'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:202:in `each'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:202:in `build_extensions'
#14 31.80   /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:843:in `build_extensions'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/rubygems_gem_installer.rb:72:in
#14 31.80 `build_extensions'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/rubygems_gem_installer.rb:28:in
#14 31.80 `install'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/source/rubygems.rb:202:in
#14 31.80 `install'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/installer/gem_installer.rb:54:in
#14 31.80 `install'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/installer/gem_installer.rb:16:in
#14 31.80 `install_from_spec'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/installer/parallel_installer.rb:156:in
#14 31.80 `do_install'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/installer/parallel_installer.rb:147:in
#14 31.80 `block in worker_pool'
#14 31.80   /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/worker.rb:62:in `apply_func'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/worker.rb:57:in `block in
#14 31.80 process_queue'
#14 31.80   /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/worker.rb:54:in `loop'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/worker.rb:54:in
#14 31.80 `process_queue'
#14 31.80 /usr/local/bundle/gems/bundler-2.4.16/lib/bundler/worker.rb:90:in `block (2
#14 31.80 levels) in create_threads'
#14 31.80 
#14 31.80 An error occurred while installing unf_ext (0.0.8.2), and Bundler cannot
#14 31.80 continue.
#14 31.80 
#14 31.80 In Gemfile:
#14 31.80   sequenceserver was resolved to 2.1.0, which depends on
#14 31.80     rest-client was resolved to 2.1.0, which depends on
#14 31.80       http-cookie was resolved to 1.0.5, which depends on
#14 31.80         domain_name was resolved to 0.5.20190701, which depends on
#14 31.80           unf was resolved to 0.1.4, which depends on
#14 31.80             unf_ext
------
executor failed running [/bin/sh -c bundle install --without=development]: exit code: 5
```

**Comment by nathanweeks** [comment]
Closed by #675
