### ISSUE TITLE
NoMethodError for SequenceServer.makeblastdb.any_to_format?

### ISSUE THREAD

**Issue by thekswenson** [wurmlab/sequenceserver#707]
I have a db directory with a single fasta file with a single sequence in it.  I see a NoMethodError when I ask it to create a blast database:

```
Could not find BLAST+ databases in: /home/username/home/software/sequenceserverdb.

Search for FASTA files (.fa, .fasta, .fna) in '/home/username/home/software/sequenceserverdb' and try
creating BLAST+ databases? [y/n] (Default: y).

>> 

Searching ...
/var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/bin/sequenceserver:304:in `rescue in block (2 levels) in <top (required)>': private method `any_to_format?' called for #<SequenceServer::MAKEBLASTDB:0x00007f607f6b13b8 @database_dir="/home/username/home/software/sequenceserverdb", @formatted_fastas=[]> (NoMethodError)

            if SequenceServer.makeblastdb.any_to_format?
                                         ^^^^^^^^^^^^^^^
Did you mean?  any_formatted?
	from /var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/bin/sequenceserver:184:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/3.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /var/lib/gems/3.1.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/bin/sequenceserver:48:in `<top (required)>'
	from /usr/local/bin/sequenceserver:25:in `load'
	from /usr/local/bin/sequenceserver:25:in `<main>'
/var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/lib/sequenceserver.rb:207:in `init_database': Could not find BLAST+ databases in: /home/username/home/software/sequenceserverdb. (SequenceServer::NO_BLAST_DATABASE_FOUND)
	from /var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/lib/sequenceserver.rb:83:in `init'
	from /var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/bin/sequenceserver:185:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/3.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /var/lib/gems/3.1.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /var/lib/gems/3.1.0/gems/sequenceserver-2.2.0/bin/sequenceserver:48:in `<top (required)>'
	from /usr/local/bin/sequenceserver:25:in `load'
	from /usr/local/bin/sequenceserver:25:in `<main>'
```

**Comment by yannickwurm** [comment]
Hmm - I see you're on ruby 3.1 but the error message still surprises me (and if there is an error, we should be catching it elegantly). Something that we may not have fully test coverage for may have broken in a recent update. 

However, it's late Friday night so I doubt we'll be able to debug before Monday. In the meantime, 
you can try `makeblastdb -parse_seqids -hash_index -in MYGENOME.fasta -dbtype nucl `
